spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db/test-task
    username: dmitry
    password: dmitry
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: none
server:
  port: 8081
